-- AlterTable
ALTER TABLE `results` ADD COLUMN `accessories` TEXT NULL,
    ADD COLUMN `case` VARCHAR(255) NULL,
    ADD COLUMN `cooler` VARCHAR(255) NULL,
    ADD COLUMN `cpu` VARCHAR(255) NULL,
    ADD COLUMN `fans` TEXT NULL,
    ADD COLUMN `gpu` VARCHAR(255) NULL,
    ADD COLUMN `mobo` VARCHAR(255) NULL,
    ADD COLUMN `psu` VARCHAR(255) NULL,
    ADD COLUMN `ram` VARCHAR(255) NULL,
    ADD COLUMN `ssd` TEXT NULL;
